export const fallbackCopies: any = {
    login: {
        "account": "Inicia sesión o crea tu cuenta en Sumer",
        "phone":"Celular de tu negocio",
        "agree":"Acepto los",
        "terms":"términos y condiciones",
        "sms":"Recibir código por SMS",
        "whatsapp": "Recibir código por WhatsApp",
        "name":"Nombre",
        "last-name":"Apellido",
        "ready":"Listo",
        "code":"Ingresa el código que te enviamos",
        "send":"El código fue enviado al",
        "send-again":"Volver a enviar",
        "next":"Siguiente",
        "incorrect":"El código no coincide, inténtalo de nuevo.",
        "resend":"Código enviado correctamente",
        "logout": "Cerrar sesión",
        "helpMessage": "¡Hola! Sumer hoy quisiera preguntarles acerca de:",
        "support": "¿Necesitas ayuda?",
        "codeQuestion": "¿No recibiste tú código?",
        "loginQuestion": "¿Ya tienes una cuenta?",
        "loginAction": "Iniciar sesión",
        "invalidPhoneNumber": "El número de teléfono no es válido",
        "invalidEmail": "El Email no es válido",
        "logoutTitle": "Cerrar sesión",
        "logoutMessage": "¿Estás seguro que deseas cerrar sesión?",
        "logoutConfirm": "Si",
        "logoutCancel": "No",
        "error": "ocurrió un error, intente nuevamente",
        "facebook_login": "Continuar con Facebook",
        "google_login": "Continuar con Google",
        "apple_login": "Continuar con Apple",
        "phone_login": "Continuar con teléfono",
        "email": "Continuar con correo",
        "title": "Iniciar sesión",
        "number_phone": "Escribe tu número de celular con el que creaste tu cuenta en Sumer",
        "continue": "Continuar",
        "do_not_have_account": "¿No tienes una cuenta?",
        "register_now": "Regístrate ahora",
        "register": "Regístrate en Sumer",
        "code_verification": "Código de verificación",
        "code_verification_send": "Hemos enviado un código de verificación via SMS a:",
        "change_phone": "Cambiar",
        "login_sumer": "Iniciar sesión en Sumer",
        "login_qr":{
            "title": "Iniciar sesión en Sumer Web por código QR",
            "step_1": "Ingresa a la app de Sumer en tu teléfono",
            "step_2": "Gestión de tu negocio",
            "step_3": "Luego ve a la sección visibilidad y haz clic en el botón \"SUMER WEB\"",
            "step_4": "Haz clic en el botón \"Vincular un dispositivo\"",
            "step_5": "Cuando se active la cámara escanea este código QR",
            "help": "¿Necesitas ayuda?"
        }
    },
    register: {
        "not_account": "Aún no tienes una cuenta en Sumer.",
        "download_app": "Descarga la app y crea tu cuenta",
    },
    download_app: "Descargar la app",
}